DROP TABLE IF EXISTS avis CASCADE ;
DROP TABLE IF EXISTS contact CASCADE;
DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS identifiant CASCADE ;
DROP TABLE IF EXISTS option_voiture CASCADE;
DROP TABLE IF EXISTS caracteristique_voiture CASCADE;
DROP TABLE IF EXISTS image_voiture CASCADE ;
DROP TABLE IF EXISTS voiture_occassion CASCADE;
DROP TABLE IF EXISTS service_garage;
