name: Deploy to VPS

on:
  push:
    branches:
      - master

env:
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
  VPS_HOST: ${{ secrets.VPS_HOST }}
  APP_PATH: ${{ secrets.VPS_DIRECTORY }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: vps_hostinger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass

      - name: Copy files to VPS
        run: sshpass -p $VPS_PASSWORD scp -o StrictHostKeyChecking=no -r ./* $VPS_USER@$VPS_HOST:$APP_PATH

      - name: Deploy the new image
        uses: appleboy/ssh-action@master
        env:
          PATH_DIRECTORY: ${{ secrets.VPS_DIRECTORY }}
          messenger: ${{ secrets.MESSENGER_TRANSPORT_DSN }}
          url: ${{ secrets.APP_URL }}
          pwd: ${{ secrets.GARAGE_DATABASE_PASSWORD }}
          userdb: ${{ secrets.GARAGE_DATABASE_USER }}
          urldb: ${{ secrets.GARAGE_DATABASE_URL }}
          urldata: ${{ secrets.DATABASE_URL }}
          secreteapp: ${{ secrets.APP_SECRET }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          envs:  PATH_DIRECTORY,messenger,url,pwd,userdb,urldb,urldata,secreteapp
          script: |
            cd $PATH_DIRECTORY
            ls -al
            cat << EOF > .env
              MESSENGER_TRANSPORT_DSN=$messenger
              APP_URL=$url 
              GARAGE_DATABASE_PASSWORD=$pwd
              GARAGE_DATABASE_USER=$userdb
              GARAGE_DATABASE_URL=$urldb
              DATABASE_URL=$urldata
              APP_SECRET=$secreteapp 
              APP_ENV=prod
            EOF
            chmod 600 .env